### ISSUE TITLE
 "Unexpected token *"

### ISSUE THREAD

**Issue by aaronmcohen** [angular/dgeni#127] opened 2015-04-13 14:13 UTC
I as trying out Dgeni against a [KoaJS](http://koajs.com/) application however it seems to having trouble with this

app.use(function *(){
	  this.body = 'Hello World';
});

The exact error is  "Unexpected token *" and it passes eslint. 

Is there a special setting I need to use?

**Comment by hco** [comment] 2015-05-05 12:46
I assume that this is related to #122, as generators are a ES6 feature.

**Comment by aaronmcohen** [comment] 2015-05-05 14:12
Looks like it is related to the ES6 support.  Thank you!

**Comment by petebacondarwin** [comment] 2015-05-06 08:31
Closing as a dupe of #122

**Closed by petebacondarwin** 2015-05-06 08:31 UTC
