### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by wesleycho** [angular/dgeni#129] opened 2015-04-22 02:23 UTC
I get this error when trying to run dgeni on source files written in ES6 - in particular, the `export` statement at the beginning of a script.

This should not error out on ES6 scripts

**Comment by wesleycho** [comment] 2015-04-22 02:26
Investigating this further, this looks like because esprima does not support ES6.

**Comment by hco** [comment] 2015-05-05 12:45
Seems to be a duplicate of #122

**Comment by forresst** [comment] 2015-05-06 08:01
@wesleycho You are right. Does it take to replace [Esprima](https://github.com/jquery/esprima) by [Espree](https://github.com/eslint/espree). This is done for [jsdoc](https://github.com/jsdoc3/jsdoc/commit/04559dbe7d6c61303d639575741dffbdac9ef300).
What's your opinion @petebacondarwin ?

**Comment by petebacondarwin** [comment] 2015-05-06 08:32
I will update to dgeni-packages to use Espree. Closing as a duplicate of #122

**Closed by petebacondarwin** 2015-05-06 08:32 UTC
